name: 'Terraform'

on:
  pull_request:
    branches:
    - master

env:
  TF_VERSION: 0.12.29

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Setup providers configuration
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: test.txt
        FILE_DATA: "This is a sample test"